### ISSUE TITLE
itisfoundation dockerhub : current images missing

### ISSUE THREAD

**Issue by mrnicegyu11** [ITISFoundation/jupyter-math#13]
Current builds of jupyter-based dynamic services, such as jupyter-math, seem to be missing from the itisfoundation dockerhub page. 

See:
https://hub.docker.com/orgs/itisfoundation/repositories?search=jupyter

**Comment by elisabettai** [comment]
It is probably because we pushed those images to our internal registry instead of using dockerhub, see here https://git.speag.com/oSparc/docker-publisher-osparc-services/-/blob/master/config.yaml#L1

@GitHK, maybe we can the dockerhub registry and [change the address for jupyter-math](https://git.speag.com/oSparc/docker-publisher-osparc-services/-/blob/master/config.yaml#L8)? Or this will be a mess at this point?

To be consistent we should have those images on dockerhub, since the repositories are on Github, this I guess was @mrnicegyu11's expectation.

**Comment by GitHK** [comment]
We changed the policy for how these services are built and stored. The CI that builds and validates is internal and it only pushes images which are used in the end to the distribution registry.

So from now on expect no images to be public.

**Comment by mrnicegyu11** [comment]
@elisabettai I had a talk with @GitHK and @mguidon , please have a quick talk to me about this ;)
